/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsxj_pda_wdt_WDTQuery */

#ifndef _Included_com_zsxj_pda_wdt_WDTQuery
#define _Included_com_zsxj_pda_wdt_WDTQuery
#ifdef __cplusplus
extern "C" {
#endif

extern jbyteArray Java_com_zsxj_pda_wdt_WDTQuery_test(JNIEnv *, jobject, jobjectArray);

extern jbyteArray preGetWarehouses(JNIEnv *env, jobject);

extern jobjectArray getWarehouses(JNIEnv *env_b, jobject, jbyteArray jbArray);

extern jbyteArray preGetPdEntries(JNIEnv *env, jobject thiz, jint warehouseId);
extern jobjectArray getPdEntries(JNIEnv *env, jobject thiz, jbyteArray jbArray);

extern jbyteArray preGetSpecs(JNIEnv *env, jobject thiz, jint warehouseId, jstring barCode);
extern jobjectArray getSpecs(JNIEnv *env, jobject thiz, jbyteArray jbArray);

extern jbyteArray preGetInExamSpecs(JNIEnv *env, jobject thiz, jstring barcode);
extern jobjectArray getInExamSpecs(JNIEnv *env, jobject thiz, jbyteArray jbArray);

extern jbyteArray preGetPositionCount(JNIEnv *env, jobject thiz, jint warehouseId);
extern jint getPositionCount(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetPositions(JNIEnv *env, jobject thiz, jint warehouseId, jint pos, jint pageSize);
extern jobjectArray getPositions(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetPdDetails(JNIEnv *env, jobject thiz, jint pdId, jint pos, jint pageSize);
extern jobjectArray getPdDetails(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetPdDetailCount(JNIEnv *env, jobject thiz, jint pdId);
extern jint getPdDetailCount(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetPdSpecs(JNIEnv *env, jobject thiz, jint pdId, jstring jbarcode);
extern jobjectArray getPdSpecs(JNIEnv *env, jobject thiz, jbyteArray jbytes);

//extern jbyteArray preGetSuppliers(JNIEnv *env, jobject thiz);
extern jbyteArray preGetSuppliers(JNIEnv *env, jobject thiz, jint pos, jint pageSize);
extern jobjectArray getSuppliers(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetPrice(JNIEnv *env, jobject thiz, jint specId, jint providerId);
extern jobject getPrice(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetLogistics(JNIEnv *env, jobject thiz);
extern jobjectArray getLogistics(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetTradeInfo(JNIEnv *env, jobject thiz, jstring tradeOrPost);
extern jobject getTradeInfo(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetPickers(JNIEnv *env, jobject thiz);
extern jobjectArray getPickers(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetTradeGoods(JNIEnv *env, jobject thiz, jint tradeId, jint warehouseId);
extern jobjectArray getTradeGoods(JNIEnv *env, jobject thize, jbyteArray jbytes);

extern jbyteArray preGetSupplierCount(JNIEnv *env, jobject thiz);
extern jint getSupplierCount(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetShops(JNIEnv *env, jobject thiz);
extern jobjectArray getShops(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetCashSaleSpecs(JNIEnv *env, jobject thiz, jint warehouseId, jstring jbarcode);
extern jobjectArray getCashSaleSpecs(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetInterfaceWarehouses(JNIEnv *env, jobject thiz, jstring jInterfaceId);

extern jbyteArray preGetCashSaleSpecStock(JNIEnv *env, jobject thiz, int specId, int warehouseId);
extern jstring getCashSaleSpecStock(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetCustomers(JNIEnv *env, jobject thiz, jstring tel);
extern jobjectArray getCustomers(JNIEnv *env, jobject thiz, jbyteArray jbytes);

extern jbyteArray preGetCashSaleSpecsByTerm(JNIEnv *env, jobject thiz, jint warehouseId, jstring jsearchTerm);

#ifdef __cplusplus
}
#endif
#endif
