/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsxj_pda_wdt_WDTLogin */

#ifndef WDT_TDI_LOGIN_H
#define WDT_TDI_LOGIN_H
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    initTDI
 * Signature: ()I
 */
extern jint initTDI(JNIEnv *, jobject);

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    tdiProtSh1
 * Signature: ()[B
 */
extern jbyteArray tdiProtSh1(JNIEnv *env, jobject, jstring);

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    tdiProtSh2
 * Signature: ([B)[B
 */
extern jbyteArray tdiProtSh2(JNIEnv *env, jobject, jbyteArray jbArray, jstring sellerAccount);

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    tdiProtSh3
 * Signature: ([B)[B
 */
extern jbyteArray tdiProtSh3(JNIEnv *env, jobject, jbyteArray jbArray, jstring userName, jstring password);

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    tdiProtSh4
 * Signature: ([B)[B
 */
extern jbyteArray tdiProtSh4(JNIEnv *env, jobject, jbyteArray jbArray);

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    isLogin
 * Signature: ()Z
 */
extern jboolean isLogin(JNIEnv *, jobject);

/*
 * Class:     com_zsxj_pda_wdt_WDTLogin
 * Method:    logout
 * Signature: ()V
 */
extern void logout(JNIEnv *, jobject);

extern jbyteArray prepareGetUserId(JNIEnv *env, jobject thiz, jstring userName);
extern jint getUserId(JNIEnv *env, jobject thiz, jbyteArray jbuf);

extern jbyteArray prepareGetAccounts(JNIEnv *env, jobject thiz);
extern jobjectArray getAccounts(JNIEnv *env, jobject thiz, jbyteArray jbuf);

extern jbyteArray preGetUser(JNIEnv *env, jobject thiz, jstring userName);
extern jobject getUser(JNIEnv *env, jobject thiz, jbyteArray jbuf);

#ifdef __cplusplus
}
#endif
#endif
